//
//  TrendingMoviesRouter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
///Router del modulo VIPER Trending Movies
final class TrendingMoviesRouter: TrendingMoviesWireframeProtocol {
    /// Intancia del View  del modulo VIPER Trending Movies
    weak var viewController: UIViewController?
    /**
     Metodo que regresa un UIviewcontroller con la implementacion del modulo VIPER
        - Returns: Regrea un UIViewController con la implentacion del modulo VIPER.
     */
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        guard let viewController: TrendingMoviesViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "TrendingMoviesViewController") as? TrendingMoviesViewController else { return UIViewController()}
        let view = viewController
        let interactor = TrendingMoviesInteractor(movieAPI: MovieAPI())
        let router = TrendingMoviesRouter()
        let presenter = TrendingMoviesPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    ///Funcion que regresa el ResultTableViewController que despliega los resultados de busqueda
    func getResultViewController() -> UIViewController{
        guard let viewController: ResultsTableController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "ResultsTableController") as? ResultsTableController else { return UIViewController()}
        return viewController
    }
}
