//
//  TrendingMoviesPresenter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TrendingMoviesPresenter: TrendingMoviesPresenterProtocol {
    
    weak private var view: TrendingMoviesViewProtocol?
    var interactor: TrendingMoviesInteractorProtocol?
    private let router: TrendingMoviesWireframeProtocol

    init(interface: TrendingMoviesViewProtocol, interactor: TrendingMoviesInteractorProtocol?, router: TrendingMoviesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getMovies() {
        interactor?.getMovies()
    }
    
    func setMovies(result: [ListMovieProtocol]) {
        view?.loadData(movies: result)
    }
    
    func getResultViewController() -> UIViewController {
        return router.getResultViewController()
    }
    
    func getRemotImage(from stringURL: String, completion: @escaping (UIImage?) -> ()) {
        interactor?.getRemotImage(from: stringURL, completion: completion)
    }
    
    func findMovies(for string: String, completion: @escaping ([ListMovieProtocol]) -> ()) {
        interactor?.findMovies(for: string, completion: completion)
    }
    
}
