//
//  TrendingMoviesPresenter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
/// Presenter del modulo VIPER Trending Movies
final class TrendingMoviesPresenter: TrendingMoviesPresenterProtocol {
    /// Intancia del View  del modulo VIPER Trending Movies
    weak private var view: TrendingMoviesViewProtocol?
    /// Intancia del Interactor  del modulo VIPER Trending Movies
    var interactor: TrendingMoviesInteractorProtocol?
    /// Intancia del Router  del modulo VIPER Trending Movies
    private let router: TrendingMoviesWireframeProtocol
    /// Inicializador del Presenter del modulo VIPER de Trending Movies
    /// - parameters:
    ///    - interface: View del modulo ViPER
    ///    - interactor: Interactor del modulo ViPER
    ///    - router: Router del modulo VIPER
    /// - returns:
    ///   Devuelve el Presenter del modulo VIPER Trending Movies
    init(interface: TrendingMoviesViewProtocol, interactor: TrendingMoviesInteractorProtocol?, router: TrendingMoviesWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    ///Funcion que llama al interactor para obtener las las peliculas del la api de MovieDB
    func getMovies() {
        interactor?.getMovies()
    }
    ///Funcion que llama al view  para setear  las las peliculas del la api de MovieDB
    func setMovies(result: [ListMovieProtocol]) {
        view?.loadData(movies: result)
    }
    ///Funcion que llama al interactor para obtener las las peliculas deacuerdo a un criterio de busqueda del la api de MovieDB
    func findMovies(for string: String?) {
        interactor?.findMovies(for: cleanStringForSearch(string))
    }
    /// Limpia el texto a buscar
    /// - parameters:
    ///    - string: String
    func cleanStringForSearch(_ string: String?) -> String {
        return string?.count ?? 0 > 3 ? string ?? "" : ""
    }
    /// Inicializa los valores para desplegar la busqueda en ResultsTableController
    /// - parameters:
    ///    - movies: Movies
    func loadFindMovies(movies: [ListMovieProtocol]) {
        view?.resultsTableController?.filteredProducts = movies
    }
    

    
}
