//
//  TrendingMoviesProtocols.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol TrendingMoviesWireframeProtocol: AnyObject {
}
//MARK: Presenter -
protocol TrendingMoviesPresenterProtocol: AnyObject {
    func getMovies()
    func setMovies(result: [ListMovieProtocol])
    func findMovies(for string: String?)
    func loadFindMovies(movies: [ListMovieProtocol])
    func cleanStringForSearch(_ string: String?) -> String
}

//MARK: Interactor -
protocol TrendingMoviesInteractorProtocol: AnyObject {
    var presenter: TrendingMoviesPresenterProtocol?  { get set }
    func getMovies()
    func findMovies(for string: String)
    func getSearchMoviewUrlRequest(searchString : String) -> URLRequest?
    func getMoviesUrlRequest() -> URLRequest?
}

//MARK: View -
protocol TrendingMoviesViewProtocol: AnyObject {
    var presenter: TrendingMoviesPresenterProtocol?  { get set }
    var restoredState: RestorableStateProtocol { get set }
    var resultsTableController: ResultsTableController? { get set }
    var movies: [ListMovieProtocol] { get set }
    var searchResultMovies: [ListMovieProtocol] { get set }
    func loadData(movies: [ListMovieProtocol])
    func loadSearchData(movies: [ListMovieProtocol])
}
