//
//  MoviewDetailViewController.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

///ViewController que contiene la vista del Modulo Viper de MovieDetail
/// - Parameters:
///    - presenter: Intancia del Presenter del modulo VIPER
///    - Movies: Pelicula de detalle
///    - Reviews: Arreglo con las reseñas
///    - Cast: Modeo con el reparto de una pelicula
///    - SimilarMovies: Arrleglo con peliculas similares
///    - RecomendedMovies: Arreglo con peliculas recomendadas
/// - Returns: Regrea un ViewController
///
final class MovieDetailViewController: UIViewController, MoviewDetailViewProtocol {
    
    ///Pelicula de detalle
    var movie: ListMovieProtocol?
    
    ///Intancia del Presenter del modulo VIPER
    var presenter: MoviewDetailPresenterProtocol?
    
    ///Arreglo con las reseñas
    var reviews: [Review] = []
    
    ///Modeo con el reparto de una pelicula
    var cast: [Cast] = []{
        didSet{
            DispatchQueue.main.async { [weak self] in
                self?.collectionCast.reloadData()
            }
        }
    }
    
    ///Arrleglo con peliculas similares
    var similarMovies: [ListMovieProtocol] = []{
        didSet{
            DispatchQueue.main.async { [weak self] in
                self?.collectionSimilar.reloadData()
            }
        }
    }
    
    ///Arreglo con peliculas recomendadas
    var recomendedMovies: [ListMovieProtocol] = []{
        didSet{
            DispatchQueue.main.async { [weak self] in
                self?.collectionRecomendation.reloadData()
            }
        }
    }
    
    @IBOutlet weak var imgPoster: UIImageView!
    @IBOutlet weak var lblTitle: UILabel!
    @IBOutlet weak var lblDescription: UILabel!
    @IBOutlet weak var btnLike: UIButton!
    @IBOutlet weak var collectionCast: UICollectionView!{
        didSet{
            configureCastCollectionView(collectionCast)
        }
    }
    @IBOutlet weak var collectionRecomendation: UICollectionView!{
        didSet{
            configureMovieCollectionView(collectionRecomendation)
        }
    }
    @IBOutlet weak var collectionSimilar: UICollectionView!{
        didSet{
            configureMovieCollectionView(collectionSimilar)
        }
    }

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        setUpInitialInfo()
        presenter?.getSimilar(String(movie?.id ?? 0))
        presenter?.getRecomendation(String(movie?.id ?? 0))
        presenter?.getCast(String(movie?.id ?? 0))
        presenter?.findFavoriteMovie(movie?.id ?? 0)
        presenter?.getReviews(String(movie?.id ?? 0))
    }
    
    ///funcion que confirura un UICollectionView
    /// - Parameters:
    ///    - collection: UICollectionView a configurar
    private func configureMovieCollectionView(_ collection: UICollectionView){
        collection.dataSource = self
        collection.register(UINib(nibName: MovieCollectionViewCell.idetifier, bundle: nil), forCellWithReuseIdentifier: MovieCollectionViewCell.idetifier)
    }
    
    ///funcion que confirura un UICollectionView
    /// - Parameters:
    ///    - collection: UICollectionView a configurar
    private func configureCastCollectionView(_ collection: UICollectionView){
        collection.dataSource = self
        collection.register(UINib(nibName: CastCollectionViewCell.idetifier, bundle: nil), forCellWithReuseIdentifier: CastCollectionViewCell.idetifier)
    }
    
    ///funcion que carga la informacion por defecto de una pelicula
    private func setUpInitialInfo(){
        self.title = movie?.title
        lblTitle.text = movie?.title
        lblDescription.text = movie?.overview
        guard let url = movie?.urlBackdropImage else { return }
        imgPoster.loadRemoteImage(url: url)
    }
    
    ///Accion que va al presenter a lanzar la pantalla de reseñas
    /// - Parameters:
    ///    - sender: Any
    @IBAction func goToReviws(_ sender: Any) {
        presenter?.sendToReviews(reviews: reviews)
    }
    
    ///Accion que cambia el estatus de un favorito
    /// - Parameters:
    ///    - sender: Any
    @IBAction func like(_ sender: Any) {
        guard let movie = self.movie else { return }
        presenter?.favoriteMovie(movie)
    }
    
}

extension MovieDetailViewController{
    
    ///Funcion que carga en un arreglo de Movies la informacion que regresa el API de MovieDB y recarga la el UICollectionView
    /// - Parameters:
    ///     -Movies: Array de ListMovieProtocol
    func setSimilarMovies(movies: [ListMovieProtocol]) {
        self.similarMovies = movies
    }
    
    ///Funcion que carga en un arreglo de Movies la informacion que regresa el API de MovieDB y recarga la el UICollectionView
    /// - Parameters:
    ///     -Movies: Array de ListMovieProtocol
    func setRecomendedMovies(movies: [ListMovieProtocol]) {
        self.recomendedMovies = movies
    }
    
    ///Funcion que carga en un arreglo de Cast la informacion que regresa el API de MovieDB y recarga la el UICollectionView
    /// - Parameters:
    ///     -Cast: Array de Cast
    func setCast(_ cast: [Cast]) {
        self.cast = cast
    }
    
    ///Funcion que carga en un arreglo de Review la informacion que regresa el API de MovieDB
    /// - Parameters:
    ///     -reviews: Array de Review
    func setReviews(_ reviews: [Review]) {
        self.reviews = reviews
    }
    
    ///Funcion que cambia el estatus de un favorito
    /// - Parameters:
    ///     -isFavorite: conficion 
    func setFavorite(_ isFavorite: Bool) {
        btnLike.tintColor = isFavorite ? .systemPink : .systemGray
    }
    
}

extension MovieDetailViewController: UICollectionViewDataSource{
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        if collectionView == collectionCast{
            return cast.count
        }else {
            return collectionView == collectionRecomendation ? recomendedMovies.count : similarMovies.count
        }
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        if collectionView == collectionCast{
            guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: CastCollectionViewCell.idetifier, for: indexPath) as? CastCollectionViewCell else { return UICollectionViewCell() }
            let actor = cast[indexPath.row]
            guard let url = actor.urlProfilePath else { return UICollectionViewCell() }
            cell.imgActor.loadRemoteImage(url: url)
            cell.lblName.text = actor.name
            return cell
        }else{
            guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: MovieCollectionViewCell.idetifier, for: indexPath) as? MovieCollectionViewCell else { return UICollectionViewCell() }
            let movie =  collectionView == collectionRecomendation ? recomendedMovies[indexPath.row] : similarMovies[indexPath.row]
            guard let url = movie.urlImage else { return UICollectionViewCell() }
            
            cell.imgPoster.loadRemoteImage(url: url)
            cell.lblTitle.text = movie.title
            
            return cell
        }
    }
}
