//
//  MoviewDetailRouter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MovieDetailRouter: MoviewDetailWireframeProtocol {
    
    /// Intancia del View  del modulo VIPER MovieDetail
    weak var viewController: UIViewController?
    
    /**
     Metodo que regresa un UIviewcontroller con la implementacion del modulo VIPER
        - Returns: Regrea un UIViewController con la implentacion del modulo VIPER.
     */
    static func createModule(movie: ListMovieProtocol) -> UIViewController {
        let view = MovieDetailViewController(nibName: nil, bundle: nil)
        let interactor = MovieDetailInteractor(movieAPI: MovieAPI())
        let router = MovieDetailRouter()
        let presenter = MovieDetailPresenter(interface: view, interactor: interactor, router: router)
        view.movie = movie
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    /// Lanza la pantalla del detalle de una reseña
    /// - parameters:
    ///    - Review: Modelo de una reseña
    func sendToReviews(reviews: [Review]) {
        let reviewVC = ReviewsTableViewController(nibName: ReviewsTableViewController.identifier, bundle: nil)
        reviewVC.reviews = reviews
        viewController?.navigationController?.pushViewController(reviewVC, animated: true)
    }
}
