//
//  MoviewDetailPresenter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

final class MovieDetailPresenter: MoviewDetailPresenterProtocol {
    /// Intancia del View  del modulo VIPER MovieDetail
    weak private var view: MoviewDetailViewProtocol?
    /// Intancia del Interactor  del modulo VIPER MovieDetail
    var interactor: MoviewDetailInteractorProtocol?
    /// Intancia del Router  del modulo VIPER MovieDetail
    private let router: MoviewDetailWireframeProtocol
    /// Inicializador del Presenter del modulo VIPER de MovieDetail
    /// - parameters:
    ///    - interface: View del modulo ViPER
    ///    - interactor: Interactor del modulo ViPER
    ///    - router: Router del modulo VIPER
    /// - returns:
    ///   Devuelve el Presenter del modulo VIPER MovieDetail
    init(interface: MoviewDetailViewProtocol, interactor: MoviewDetailInteractorProtocol?, router: MoviewDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    ///Funcion que llama al interactor para obtener las las peliculas similares del la api de MovieDB
    func getSimilar(_ id: String) {
        interactor?.getSimilar(id)
    }
    
    ///Funcion que llama al interactor para obtener las las peliculas recomendadas del la api de MovieDB
    func getRecomendation(_ id: String) {
        interactor?.getRecomendation(id)
    }
    
    ///Funcion que llama al interactor para obtener el elenco de una pelicula del  api de MovieDB
    func getCast(_ id: String) {
        interactor?.getCast(id)
    }
    
    ///Funcion que llama al interactor para obtener las Reseñas de una pelicila  del  api de MovieDB
    func getReviews(_ id: String) {
        interactor?.getReviews(id)
    }
    
    ///Funcion que llama al interactor para actualizar el estatus de los favoritos de  peliculas del la api de MovieDB
    func favoriteMovie(_ movie: ListMovieProtocol) {
        if interactor?.findFavoriteMovie(movie.id) ?? false{
            interactor?.deleteFavorite(movie.id)
        }else{
            interactor?.saveFavorite(movie)
        }
    }
    
    ///Funcion que llama al interactor para obtener la  peliculas de los favoritos del usuario
    func findFavoriteMovie(_ id: Int) {
        let _ = interactor?.findFavoriteMovie(id)
    }
    
    ///Funcion que llama al view  para setear  las las peliculas similares del la api de MovieDB
    func setSimilarMovies(movies: [ListMovieProtocol]) {
        view?.setSimilarMovies(movies: movies)
    }
    
    ///Funcion que llama al view  para setear  las las peliculas  recomendadas del la api de MovieDB
    func setRecomendedMovies(movies: [ListMovieProtocol]) {
        view?.setRecomendedMovies(movies: movies)
    }
    
    ///Funcion que llama al view  para setear  el reparto de una pelicula
    func setCast(_ cast: [Cast]) {
        view?.setCast(cast)
    }
    
    ///Funcion que llama al view  para setear una pelicuia en los favoritos
    func setFavorite(_ isFavorite: Bool) {
        view?.setFavorite(isFavorite)
    }
    
    ///Funcion que llama al view  para setear  las reseñas en el modelo para ir a la panttalla de las reseñas
    func setReviews(_ reviews: [Review]) {
        view?.setReviews(reviews)
    }
    
    ///Funcion que llama al router para lanzar la pantalla de las reseñas
    func sendToReviews(reviews: [Review]) {
        router.sendToReviews(reviews: reviews)
    }
}
