//
//  MoviewDetailPresenter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoviewDetailPresenter: MoviewDetailPresenterProtocol {

    weak private var view: MoviewDetailViewProtocol?
    var interactor: MoviewDetailInteractorProtocol?
    private let router: MoviewDetailWireframeProtocol

    init(interface: MoviewDetailViewProtocol, interactor: MoviewDetailInteractorProtocol?, router: MoviewDetailWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    
    func getSimilar(_ id: String) {
        interactor?.getSimilar(id)
    }
    
    func getRecomendation(_ id: String) {
        interactor?.getRecomendation(id)
    }
    
    func getCast(_ id: String) {
        interactor?.getCast(id)
    }
    
    func favoriteMovie(_ movie: ListMovieProtocol) {
        if interactor?.findFavoriteMovie(movie.id) ?? false{
            interactor?.deleteFavorite(movie.id)
        }else{
            interactor?.saveFavorite(movie)
        }
    }
    
    func findFavoriteMovie(_ id: Int) {
        let _ = interactor?.findFavoriteMovie(id)
    }
    
    func setSimilarMovies(movies: [ListMovieProtocol]) {
        view?.setSimilarMovies(movies: movies)
    }
    
    func setRecomendedMovies(movies: [ListMovieProtocol]) {
        view?.setRecomendedMovies(movies: movies)
    }
    
    func setCast(_ cast: [Cast]) {
        view?.setCast(cast)
    }
    
    func setFavorite(_ isFavorite: Bool) {
        view?.setFavorite(isFavorite)
    }
}
