//
//  MoviewDetailInteractor.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoviewDetailInteractor: MoviewDetailInteractorProtocol {
    
    weak var presenter: MoviewDetailPresenterProtocol?
    /// Intancia del protocolo GenericAPIProtocol para las llamadas al Api de MovieDB
    let movieAPI: GenericAPIProtocol
    init(movieAPI: GenericAPIProtocol) {
        self.movieAPI = movieAPI
    }
    
    func getSimilar(_ id: String) {
        guard let urlRequest = ApiConstans.similar(id).urlRequest else { return }
        movieAPI.fetch(movieURLRequest: urlRequest) {[weak self] (result: Result<MovieResult?, Error>) in
            switch result {
            case .failure(let fail):
                print(fail)
            case .success(let response):
                self?.presenter?.setSimilarMovies(movies: response?.results ?? [])
            }
        }
    }
    
    func getRecomendation(_ id: String) {
        guard let urlRequest = ApiConstans.recomended(id).urlRequest else { return }
        movieAPI.fetch(movieURLRequest: urlRequest) {[weak self] (result: Result<MovieResult?, Error>) in
            switch result {
            case .failure(let fail):
                print(fail)
            case .success(let response):
                self?.presenter?.setRecomendedMovies(movies: response?.results ?? [])
            }
        }
    }
    
    func getCast(_ id: String) {
        guard let urlRequest = ApiConstans.credits(id).urlRequest else { return }
        movieAPI.fetch(movieURLRequest: urlRequest) {[weak self] (result: Result<CastResult?, Error>) in
            switch result {
            case .failure(let fail):
                print(fail)
            case .success(let response):
                self?.presenter?.setCast(response?.cast ?? [])
            }
        }
    }
    
    func deleteFavorite(_ id: Int) {
        guard let dataMovie = UserDefaults.standard.data(forKey: "favorite_movies"),
              let dctMovies: [Int : Movie] = try? JSONDecoder().decode([Int : Movie].self, from: dataMovie) else { return }
        var movies = dctMovies
        movies.removeValue(forKey: id)
        UserDefaults.standard.setValue(movies, forKey: "favorite_movies")
        presenter?.setFavorite(false)
    }
    
    func saveFavorite(_ movie: ListMovieProtocol) {
        let encoder = JSONEncoder()
        guard let movie = movie as? Movie else { return }
        let dctMovie: [Int: Movie] = [movie.id: movie]
        if let data = try? encoder.encode(dctMovie){
            UserDefaults.standard.setValue(data, forKey: "favorite_movies")
            presenter?.setFavorite(true)
        }
    }
    
    func findFavoriteMovie(_ id: Int) -> Bool{
        guard let dataMovie = UserDefaults.standard.data(forKey: "favorite_movies"),
              let dctMovies: [Int : Movie] = try? JSONDecoder().decode([Int : Movie].self, from: dataMovie) else {
            presenter?.setFavorite(false)
            return false
        }
        presenter?.setFavorite(dctMovies[id] != nil)
        return dctMovies[id] != nil
    }
    
}
