//
//  MoviewDetailRouter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 03/05/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MoviewDetailRouter: MoviewDetailWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(movie: ListMovieProtocol) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = MoviewDetailViewController(nibName: nil, bundle: nil)
        let interactor = MoviewDetailInteractor(movieAPI: MovieAPI())
        let router = MoviewDetailRouter()
        let presenter = MoviewDetailPresenter(interface: view, interactor: interactor, router: router)
        view.movie = movie
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
