//
//  TrendingMoviesProtocols.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation
import UIKit

//MARK: Wireframe -
protocol MoviesWireframeProtocol: AnyObject {
    func sendToDetail(with movie: Movie)
}
//MARK: Presenter -
protocol MoviesPresenterProtocol: AnyObject {
    func getMovies()
    func setMovies(result: [ListMovieProtocol])
    func findMovies(for string: String?)
    func loadFindMovies(movies: [ListMovieProtocol])
    func cleanStringForSearch(_ string: String?) -> String
    func sendToDetail(movie: Movie)
}

//MARK: Interactor -
protocol MoviesInteractorProtocol: AnyObject {
    var presenter: MoviesPresenterProtocol?  { get set }
    func getMovies(urlRequest: URLRequest)
    func getLocalMovies()
    func findMovies(for string: String)
}

//MARK: View -
protocol MoviesViewProtocol: AnyObject {
    var type: (ViewPropertiesProtocol & ApiPathProtocol)? { get  set}
    var presenter: MoviesPresenterProtocol?  { get set }
    var restoredState: RestorableStateProtocol { get set }
    var resultsTableController: ResultsTableController? { get set }
    var movies: [ListMovieProtocol] { get set }
    var searchResultMovies: [ListMovieProtocol] { get set }
    func loadData(movies: [ListMovieProtocol])
    func loadSearchData(movies: [ListMovieProtocol])
}
