//
//  TrendingMoviesRouter.swift
//  BAZProject
//
//  Created Octavio Labastida Luna on 19/04/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
///Router del modulo VIPER Trending Movies
final class MoviesRouter: MoviesWireframeProtocol {
    /// Intancia del View  del modulo VIPER Trending Movies
    weak var viewController: UIViewController?
    /**
     Metodo que regresa un UIviewcontroller con la implementacion del modulo VIPER
        - Returns: Regrea un UIViewController con la implentacion del modulo VIPER.
     */
    static func createModule(type: ViewPropertiesProtocol & ApiPathProtocol) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        guard let view: MoviesViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "TrendingMoviesViewController") as? MoviesViewController else { return UIViewController() }
        
        let interactor = MoviesInteractor(movieAPI: MovieAPI())
        let router = MoviesRouter()
        let presenter = MoviesPresenter(interface: view, interactor: interactor, router: router)
        view.type = type
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    /// Lanza la pantalla del detalle de una pelicula
    /// - parameters:
    ///    - Movie: Modelo de una pelicula
    func sendToDetail(with movie: Movie) {
        viewController?.navigationController?.pushViewController(MovieDetailRouter.createModule(movie: movie), animated: true)
    }
}
